version: '2'
services:
  db:
    image: postgres:12.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/pri_image_talk
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - "TZ=Japan"
  redis:
    image: redis
  worker:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/pri_image_talk
    links:
      - db
      - redis
    environment:
      - ENABLE_BOOTSNAP=false
