:daemon: false
:concurrency: 8
production:
  :concurrency: 10
:queues:
  - create_tweet
  - regular_tweet
  - slack_notification
:schedule:
  RegularTweetWorker:
    cron: '0 */30 * * * *' # execute at every 30 minutes
