:daemon: false
:concurrency: 8
production:
  :concurrency: 10
:queues:
  - create_tweet
  - regular_tweet
  - slack_notification
  - fetch_mention
:schedule:
  RegularTweetWorker:
    cron: '0 */30 * * * *' # execute at every 30 minutes
  FetchMentionWorker:
    cron: '*/10 * * * * *' # execute at every 10 seconds
